name: "MongoDB Health Check via SSM"

on:
  push:
    branches:
      - staging
  workflow_dispatch: {}

jobs:
  check-mongodb:
    name: "Check MongoDB Status"
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      # Set the appropriate workspace and token for the staging environment
      TF_WORKSPACE: wiz-tasky-staging
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN_STAGING }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init

      - name: Retrieve MongoDB Instance ID
        id: mongodb
        run: |
          INSTANCE_ID=$(terraform output -raw mongodb_instance_id)
          echo "::set-output name=instance_id::$INSTANCE_ID"
      
      - name: Run MongoDB Ping via SSM
        env:
          INSTANCE_ID: ${{ steps.mongodb.outputs.instance_id }}
        run: |
          echo "Running SSM command on MongoDB instance: $INSTANCE_ID"
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=$INSTANCE_ID" \
            --parameters 'commands=["mongo --eval \"db.runCommand({ ping: 1 })\""]' \
            --timeout-seconds 30 \
            --query "Command.CommandId" \
            --output text \
            --region $AWS_REGION)
          echo "Command ID: $COMMAND_ID"
          # Wait briefly for the command to complete
          sleep 10
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --region $AWS_REGION
