name: "MongoDB Health Check via SSM"

on:
  push:
    branches:
      - dev
      - staging
  workflow_dispatch: {}

jobs:
  check-mongodb:
    name: "Check MongoDB Status"
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      # Set TF_WORKSPACE dynamically: staging branch gets wiz-tasky-staging; otherwise, use wiz-tasky-dev.
      TF_WORKSPACE: ${{ github.ref == 'refs/heads/staging' && 'wiz-tasky-staging' || 'wiz-tasky-dev' }}
      # Select the correct Terraform Cloud API token based on the branch.
      TF_TOKEN_app_terraform_io: ${{ github.ref == 'refs/heads/staging' && secrets.TF_API_TOKEN_STAGING || secrets.TF_API_TOKEN_DEV }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init

      - name: Retrieve MongoDB Instance ID
        id: mongodb
        run: |
          INSTANCE_ID=$(terraform output -raw mongodb_instance_id)
          echo "MongoDB Instance ID: ${INSTANCE_ID}"
          echo "instance_id=${INSTANCE_ID}" >> $GITHUB_OUTPUT

      - name: Run MongoDB Ping via SSM
        run: |
          INSTANCE_ID="${{ steps.mongodb.outputs.instance_id }}"
          echo "Running SSM command on MongoDB instance: ${INSTANCE_ID}"
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=${INSTANCE_ID}" \
            --parameters 'commands=["mongo --eval \"db.runCommand({ ping: 1 })\""]' \
            --timeout-seconds 30 \
            --query "Command.CommandId" \
            --output text \
            --region $AWS_REGION)
          echo "Command ID: ${COMMAND_ID}"
          sleep 10
          aws ssm get-command-invocation \
            --command-id "${COMMAND_ID}" \
            --instance-id "${INSTANCE_ID}" \
            --region $AWS_REGION
