name: "MongoDB Health Check via SSM"

on:
  push:
    branches:
      - dev
      - staging
  workflow_dispatch: {}

jobs:
  check-mongodb:
    name: "Check MongoDB Status"
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      # Dynamically set Terraform workspace and token based on branch:
      TF_WORKSPACE: ${{ github.ref == 'refs/heads/staging' && 'wiz-tasky-staging' || 'wiz-tasky-dev' }}
      TF_TOKEN_app_terraform_io: ${{ github.ref == 'refs/heads/staging' && secrets.TF_API_TOKEN_STAGING || secrets.TF_API_TOKEN_DEV }}
      AWS_ACCESS_KEY_ID: ${{ github.ref == 'refs/heads/staging' && secrets.AWS_ACCESS_KEY_ID_STAGING || github.ref == 'refs/heads/main' && secrets.AWS_ACCESS_KEY_ID_PROD || secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ github.ref == 'refs/heads/staging' && secrets.AWS_SECRET_ACCESS_KEY_STAGING || github.ref == 'refs/heads/main' && secrets.AWS_SECRET_ACCESS_KEY_PROD || secrets.AWS_SECRET_ACCESS_KEY_DEV }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.5"

      - name: Terraform Init
        run: terraform init

      - name: Retrieve MongoDB Instance ID
        id: mongodb
        run: |
          # Run terraform output and capture all output
          OUTPUT=$(terraform output -raw mongodb_instance_id 2>/dev/null)
          echo "Raw output: $OUTPUT"
          # Extract the instance ID using grep with a regex that matches IDs starting with "i-"
          INSTANCE_ID=$(echo "$OUTPUT" | grep -oE 'i-[0-9a-f]+')
          echo "MongoDB Instance ID: ${INSTANCE_ID}"
          echo "instance_id=${INSTANCE_ID}" >> $GITHUB_OUTPUT

      - name: Run MongoDB Ping via SSM
        run: |
          INSTANCE_ID="${{ steps.mongodb.outputs.instance_id }}"
          echo "Running SSM command on MongoDB instance: ${INSTANCE_ID}"
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=${INSTANCE_ID}" \
            --parameters commands=["mongosh --quiet --eval 'db.runCommand({ ping: 1 })'"] \
            --timeout-seconds 30 \
            --query "Command.CommandId" \
            --output text \
            --region $AWS_REGION)
          echo "Command ID: ${COMMAND_ID}"
          sleep 10
          aws ssm get-command-invocation \
            --command-id "${COMMAND_ID}" \
            --instance-id "${INSTANCE_ID}" \
            --region $AWS_REGION
