name: "Terraform Deploy & Remediate"

on:
  workflow_dispatch:  # Allows manual triggering with inputs
    inputs:
      remediation_mode:
        description: "Set to true for remediated (secure) configuration"
        required: true
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN_PROD }}
      TF_WORKSPACE: wiz-tasky-prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply Remediation
        run: terraform apply -auto-approve -var="remediation_mode=${{ github.event.inputs.remediation_mode }}"
