name: "Terraform CI/CD"

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS OIDC Authentication
        id: aws-auth
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActionsTerraform
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init

      - name: Select Terraform Workspace
        run: terraform workspace select wiz-tasky-dev || terraform workspace new wiz-tasky-dev

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply (Dev)
        if: github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve

      - name: Require Manual Approval for Staging/Prod
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
        uses: hmarr/auto-approve-action@v3

      - name: Terraform Apply (Staging/Prod)
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
