name: "Terraform Quality Checks"

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    env:
      # Set TF_WORKSPACE dynamically based on the branch.
      TF_WORKSPACE: ${{ github.ref == 'refs/heads/main' && 'wiz-tasky-prod' || github.ref == 'refs/heads/staging' && 'wiz-tasky-staging' || 'wiz-tasky-dev' }}
      # Set the appropriate Terraform Cloud API token for the environment.
      TF_TOKEN_app_terraform_io: ${{ github.ref == 'refs/heads/main' && secrets.TF_API_TOKEN_PROD || github.ref == 'refs/heads/staging' && secrets.TF_API_TOKEN_STAGING || secrets.TF_API_TOKEN_DEV }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
