name: "Terraform CI/CD"

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN_DEV }}
      TERRAFORM_WORKSPACE: "wiz-tasky-dev"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Environment Variables for Staging & Prod
        if: github.ref == 'refs/heads/staging'
        run: echo "TF_API_TOKEN=${{ secrets.TF_API_TOKEN_STAGING }}" >> $GITHUB_ENV && echo "TERRAFORM_WORKSPACE=wiz-tasky-staging" >> $GITHUB_ENV

      - name: Set Environment Variables for Prod
        if: github.ref == 'refs/heads/main'
        run: echo "TF_API_TOKEN=${{ secrets.TF_API_TOKEN_PROD }}" >> $GITHUB_ENV && echo "TERRAFORM_WORKSPACE=wiz-tasky-prod" >> $GITHUB_ENV

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init -backend-config="hostname=app.terraform.io" -backend-config="organization=wiz-tasky-org" -backend-config="workspaces.name=$TERRAFORM_WORKSPACE"

      - name: Terraform Plan
        run: terraform plan -var="terraform_workspace=$TERRAFORM_WORKSPACE" -input=false

      - name: Terraform Apply (Dev)
        if: github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve

      - name: Require Manual Approval for Staging/Prod
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
        uses: hmarr/auto-approve-action@v3

      - name: Terraform Apply (Staging/Prod)
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
